### ISSUE TITLE
Support the "global blackboard" pattern and callback in the while loop

### ISSUE THREAD

**Issue by facontidavide** [MarqRazz/ActionServer.BT#5]
I would like to find a way to support this pattern:
https://github.com/BehaviorTree/BehaviorTree.CPP/blob/master/examples/t19_global_blackboard.cpp

Some users will probably want to interact with this "global blackboard" in the tree execution while loop.

This may also require an additional callback in the loop:
```c++
while (rclcpp::ok() && status == BT::NodeStatus::RUNNING)
```

**Comment by MarqRazz** [comment]
I added this functionality as part of #1. Let me know what you think over there.
